name: Docker Build

on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [ frontend, backend ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Build Docker image for ${{ matrix.component }}
        run: |
          docker build -t golink-${{ matrix.component }}:${{ github.sha }} ${{ matrix.component }}
