name: Docker Build

on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [ frontend, backend ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Build Docker image for ${{ matrix.component }}
        run: |
          docker build -t golink-${{ matrix.component }}:${{ github.sha }} ${{ matrix.component }}
