name: Frontend Lint

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  frontend-lint:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: ./frontend/.node-version

      - name: Install devDependencies
        run: npm ci --only=dev
        working-directory: ./frontend

      - name: Run Biome
        run: npm run lint
        working-directory: ./frontend
